### ISSUE TITLE
Error running example

### ISSUE THREAD

**Issue by jgwinner** [botbits/serverless-loopback#4]
When running the sample pretty much as is (I did change to Oregon), I get the following error:

```
Serverless Error ---------------------------------------

  An error occurred: IamRoleLambdaExecution - API: iam:AttachRolePolicy User: arn:aws:iam::redacted:user/serverless-agent is not authorized to perform: iam:AttachRolePolicy on resource: role serverless-loopback-dev-us-west-2-lambdaRole.

```

What's weirder, is that I went to add "AttachRolePolicy" but couldn't find it in the list.

I get the same error if I run on east. 

        == John ==

**Comment by jgwinner** [comment]
Ok, it's definitely a permissions error, if I add administrator access it does this:

```
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: WARNING: Function loopback has timeout of 60 seconds, however, it's attached to API Gateway so it's automatically limited to 30 seconds.
Serverless: WARNING: Function loopback has timeout of 60 seconds, however, it's attached to API Gateway so it's automatically limited to 30 seconds.
Serverless: Service files not changed. Skipping deployment...
Service Information
service: serverless-loopback
stage: dev
region: us-west-2
stack: serverless-loopback-dev
resources: 1
api keys:
  None
endpoints:
  None
functions:
  loopback: dev-loopback
layers:
  None

Stack Outputs
ServerlessDeploymentBucketName: serverless-loopback-dev-serverlessdeploymentbucke-redacted
```

At least I have a work around.

**Comment by marcelobern** [comment]
@jgwinner serverless is a bit "greedy" on permissions.

As you can [read](https://serverless.com/framework/docs/providers/aws/guide/credentials/) here: "Note: In a production environment, we recommend reducing the permissions to the IAM User which the Framework uses. Unfortunately, the Framework's functionality is growing so fast, we can't yet offer you a finite set of permissions it needs (we're working on this)."

**Comment by jgwinner** [comment]
Understood, and I did read that, but my point is that you should be able to download the sample, read the docs, and implement. I followed them, so if there is a need for higher permission levels, that should be added to the sample and instructions for running.
