### ISSUE TITLE
Can run, cleanup, run

### ISSUE THREAD

**Issue by jgwinner** [botbits/serverless-loopback#5]
While working on issue https://github.com/botbits/serverless-loopback/issues/4 I tried to run:

`npm run sls-cleanup`

then 

`npm run sls-deploy `

but I got this error:

```
  Serverless Error ---------------------------------------


  An error occurred: IamRoleLambdaExecution - serverless-loopback-dev-us-west-2-lambdaRole already exists.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     OS:                     linux
     Node Version:           8.10.0
     Serverless Version:     1.42.3

```

# Expected behavior:

Either the create should skip trying to create the role, OR the sls-cleanup should also clean up the extra role.

Is this a Botbits error or a serverless error? My guess is, both of these are the latter.

        == John ==

**Comment by marcelobern** [comment]
@jgwinner yes, this is a serverless error as the sample provided does not create code per se:
- All files under `lib` are really loopback ones.
- The `serverless.yml` file just creates a serverless config for the deployment.

As you can see from the serverless documentation [here](https://serverless.com/framework/docs/providers/aws/guide/iam#the-default-iam-role) the role in question is actually the default role created by serverless.

My guess on why you might be running into this issue would be that you may be trying to remove the cloud formation stack before it is finished creating. Have you tried looking directly at the AWS CloudFormation console during the creation process?

**Comment by jgwinner** [comment]
Yes, I had, but I believe that the error, above, might have been 'stuff' left over after running into the permissions error referenced by https://github.com/botbits/serverless-loopback/issues/4 

Honestly, I haven't run into it again, I'm just deploying. I kept getting a 404 error via loopback even though my DB tier permissions were correct, so temporarily we're using a free tier for the Loopback portion, so I quit working on the Lambda's. If I get a chance to retry, I'll see if a fresh update with promiscuous permissions is removable. Sorry for the vague confirmation, thanks for taking a look.
